/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author omaci
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
        
        
        //TextFieldUsuario.putClientProperty("JComponent.rountReact", 100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelLogin = new Vista.PanelRound();
        Inovahouse = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        TextFieldUsuario = new javax.swing.JTextField();
        TextFieldcontraseña = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelLogin.setBackground(new java.awt.Color(39, 33, 105));
        PanelLogin.setForeground(new java.awt.Color(39, 33, 105));
        PanelLogin.setPreferredSize(new java.awt.Dimension(500, 650));
        PanelLogin.setRoundBottomLeft(50);
        PanelLogin.setRoundBottomRight(50);
        PanelLogin.setRoundTopLeft(50);
        PanelLogin.setRoundTopRight(50);
        PanelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Inovahouse.setBackground(new java.awt.Color(255, 255, 255));
        Inovahouse.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Inovahouse.setForeground(new java.awt.Color(255, 255, 255));
        Inovahouse.setText("INOVAHOUSE");
        PanelLogin.add(Inovahouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, -1, -1));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/image1.png"))); // NOI18N
        PanelLogin.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, -1, -1));

        TextFieldUsuario.setText("Usuario");
        TextFieldUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldUsuarioActionPerformed(evt);
            }
        });
        PanelLogin.add(TextFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 300, 40));

        TextFieldcontraseña.setText("Contraseña");
        TextFieldcontraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldcontraseñaActionPerformed(evt);
            }
        });
        PanelLogin.add(TextFieldcontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 300, 40));

        jRadioButton1.setText("jRadioButton1");
        PanelLogin.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, -1, -1));

        jButton1.setText("jButton1");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        jButton1.setMargin(new java.awt.Insets(20, 14, 3, 14));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        PanelLogin.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 530, 200, 50));

        getContentPane().add(PanelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 500, 650));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/fondo.png"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldcontraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldcontraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldcontraseñaActionPerformed

    private void TextFieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldUsuarioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Inovahouse;
    private javax.swing.JLabel Logo;
    private Vista.PanelRound PanelLogin;
    private javax.swing.JTextField TextFieldUsuario;
    private javax.swing.JTextField TextFieldcontraseña;
    private javax.swing.JButton jButton1;
    private javax.swing.JRadioButton jRadioButton1;
    // End of variables declaration//GEN-END:variables
}
