/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.MenuAdminProyectos;

import Controlador.ConexionBD;
import Modelo.Torre;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import Controlador.TorreService;
import Modelo.InmuebleDAO;
import Modelo.TorreDAO;
import javax.swing.JOptionPane;
/**
 *
 * @author omaci
 */
public class CrearInmueble extends javax.swing.JFrame {
    
    private Map<String, Integer> torreMap = new HashMap<>();
    private TorreService torreService;
    
  
   
    public CrearInmueble() {
        initComponents();
        setLocationRelativeTo(null);
        ConexionBD conexionBD = new ConexionBD();
        TorreDAO torreDAO = new TorreDAO(conexionBD.getConnection("Admin"));
        this.torreService = new TorreService(torreDAO);
        llenarComboBoxTorres();
    }
    
    
     private void llenarComboBoxTorres() {
        List<Torre> torres = torreService.obtenerTorresBasicas();
        
        jctorre.removeAllItems(); 
        for (Torre torre : torres) {
            String numeroTorreStr = String.valueOf(torre.getNumerotorre());
            jctorre.addItem(numeroTorreStr);
            torreMap.put(numeroTorreStr, torre.getIdtorre());
        }
    }



    // Método para obtener el ID de la torre seleccionada en jctorre
    private Integer obtenerIdTorreSeleccionada() {
        String numeroTorreSeleccionado = (String) jctorre.getSelectedItem();
        return torreMap.get(numeroTorreSeleccionado); // Devuelve el idTorre asociado
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rSButtonMetro1 = new Vista.RSButtonMetro();
        jtmatricula = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtvalor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtnumeroinmueble = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtarea = new javax.swing.JTextField();
        jctipo = new javax.swing.JComboBox<>();
        jctorre = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(710, 440));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(710, 440));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Nuevo Inmueble");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Torre");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 120, -1, -1));

        rSButtonMetro1.setBackground(new java.awt.Color(0, 191, 99));
        rSButtonMetro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/save.png"))); // NOI18N
        rSButtonMetro1.setText("Guardar");
        rSButtonMetro1.setColorHover(new java.awt.Color(8, 136, 74));
        rSButtonMetro1.setColorNormal(new java.awt.Color(0, 191, 99));
        rSButtonMetro1.setColorPressed(new java.awt.Color(8, 136, 74));
        rSButtonMetro1.setContentAreaFilled(true);
        rSButtonMetro1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rSButtonMetro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro1ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonMetro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, 200, 60));
        jPanel1.add(jtmatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 290, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Valor");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jtvalor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtvalorActionPerformed(evt);
            }
        });
        jPanel1.add(jtvalor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 290, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Numero Inmueble");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 160, -1));
        jPanel1.add(jtnumeroinmueble, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 160, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Area (m2)");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, -1, -1));
        jPanel1.add(jtarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 100, 40));

        jctipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar...", "Apartemento", "Garaje", "Local" }));
        jctipo.setBorder(null);
        jctipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jctipoActionPerformed(evt);
            }
        });
        jPanel1.add(jctipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 100, 50));

        jctorre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jctorre.setBorder(null);
        jctorre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jctorreActionPerformed(evt);
            }
        });
        jPanel1.add(jctorre, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, 100, 50));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Matricula");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Tipo");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonMetro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro1ActionPerformed
    try {
        // Obtener valores del formulario
        String matriculaStr = jtmatricula.getText().trim();
        String numeroInmuebleStr = jtnumeroinmueble.getText().trim();
        String valorStr = jtvalor.getText().trim();
        String areaStr = jtarea.getText().trim();
        String tipo = (String) jctipo.getSelectedItem();
        Integer idTorre = obtenerIdTorreSeleccionada();

        // Validaciones básicas
        if (matriculaStr.isEmpty() || numeroInmuebleStr.isEmpty() || valorStr.isEmpty() ||
            areaStr.isEmpty() || tipo.equals("Seleccionar...") || idTorre == null) {
            JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Convertir los valores
        int matricula = Integer.parseInt(matriculaStr);
        int numeroInmueble = Integer.parseInt(numeroInmuebleStr);
        long valorInmueble = Long.parseLong(valorStr);
        int area = Integer.parseInt(areaStr);

        // Crear la conexión y el DAO
        ConexionBD conexionBD = new ConexionBD();
        InmuebleDAO inmuebleDAO = new InmuebleDAO(conexionBD.getConnection("Admin"));

        // Llamar al método insertarInmueble del DAO
        boolean resultado = inmuebleDAO.insertarInmueble(matricula, numeroInmueble, valorInmueble, null, area, idTorre, tipo);

        if (resultado) {
            JOptionPane.showMessageDialog(this, "Inmueble guardado exitosamente.");
            dispose(); // Cierra la ventana actual
        } else {
            JOptionPane.showMessageDialog(this, "Error al guardar el inmueble.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Por favor, ingrese valores numéricos válidos en los campos correspondientes.", "Error", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Ocurrió un error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_rSButtonMetro1ActionPerformed

    private void jctipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jctipoActionPerformed
      
    }//GEN-LAST:event_jctipoActionPerformed

    private void jctorreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jctorreActionPerformed
        
    }//GEN-LAST:event_jctorreActionPerformed

    private void jtvalorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtvalorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtvalorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearInmueble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearInmueble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearInmueble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearInmueble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearInmueble().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jctipo;
    private javax.swing.JComboBox<String> jctorre;
    private javax.swing.JTextField jtarea;
    private javax.swing.JTextField jtmatricula;
    private javax.swing.JTextField jtnumeroinmueble;
    private javax.swing.JTextField jtvalor;
    private Vista.RSButtonMetro rSButtonMetro1;
    // End of variables declaration//GEN-END:variables
}
